USE sanitat;
-- 1
SELECT HOSPITAL_COD, NOM, TELEFON
FROM HOSPITAL;

-- 2
SELECT HOSPITAL_COD, NOM, TELEFON
FROM HOSPITAL WHERE NOM LIKE '_a%';

-- 3
SELECT HOSPITAL_COD, SALA_COD, EMPLEAT_NO, COGNOM
FROM PLANTILLA;

-- 4
SELECT HOSPITAL_COD, SALA_COD, EMPLEAT_NO, COGNOM
FROM PLANTILLA WHERE TORN != 'N';

-- 5
SELECT * FROM MALALT
WHERE DATA_NAIX LIKE '1960-__-__';

-- 6
SELECT * FROM MALALT
WHERE DATA_NAIX >= '1960-01-01';

-- 7
SELECT COUNT(*), SEXE
FROM MALALT
GROUP BY SEXE;

-- 8
